### ISSUE TITLE
[stable/keycloak] User sessions cache is not replicated across Keycloak pods

### ISSUE THREAD

**Issue by brianupskill** [helm/charts#10561]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug+Request for Help

**Version of Helm and Kubernetes**: Helm v2.11, Kubernetes 1.8.3

**Which chart**: stable/keycloak 1.2.0

**What happened**: User sessions cache is not replicated across Keycloak pods. Even when the `CACHE_OWNERS` environment variable is passed in. In the admin console, however, I can see all the sessions from all the pods. 

**What you expected to happen**: Keycloak to correctly introspect access tokens that were generated from other keycloak pods.

**How to reproduce it** (as minimally and precisely as possible):
Start keycloak pod1
Login with pod1
Start keycloak pod2
Delete keycloak pod1
Request introspection with pod2
**FAILS** HTTP STATUS 200 `{"active":"false}`

**Anything else we need to know**: The pods are deployed by setting the `keycloak.replicas` to be greater than one.

This is the output of the cache part of `standalone-ha.xml`
```
        <subsystem xmlns="urn:jboss:domain:infinispan:4.0">
            <cache-container name="keycloak" jndi-name="infinispan/Keycloak">
                <transport lock-timeout="60000"/>
                <local-cache name="realms">
                    <eviction strategy="LRU" max-entries="10000"/>
                </local-cache>
                <local-cache name="users">
                    <eviction strategy="LRU" max-entries="10000"/>
                </local-cache>
                <local-cache name="authorization">
                    <eviction strategy="LRU" max-entries="10000"/>
                </local-cache>
                <local-cache name="keys">
                    <eviction strategy="LRU" max-entries="1000"/>
                    <expiration max-idle="3600000"/>
                </local-cache>
                <replicated-cache name="work" mode="SYNC"/>
                <distributed-cache name="sessions" mode="SYNC" owners="${env.CACHE_OWNERS:2}"/>
                <distributed-cache name="authenticationSessions" mode="SYNC" owners="${env.CACHE_OWNERS:2}"/>
                <distributed-cache name="offlineSessions" mode="SYNC" owners="${env.CACHE_OWNERS:2}"/>
                <distributed-cache name="clientSessions" mode="SYNC" owners="1"/>
                <distributed-cache name="offlineClientSessions" mode="SYNC" owners="1"/>
                <distributed-cache name="loginFailures" mode="SYNC" owners="${env.CACHE_OWNERS:2}"/>
                <distributed-cache name="actionTokens" mode="SYNC" owners="2">
                    <eviction strategy="NONE" max-entries="-1"/>
                    <expiration interval="300000" max-idle="-1"/>
                </distributed-cache>
            </cache-container>
```

**Comment by brianupskill** [comment]
Would the clientSessions set to "1" be a problem?

**Comment by bonehead06** [comment]
@brianupskill If you leave both pods up, do you see the pods communicating to each other with jgroups?

**Comment by brianupskill** [comment]
@bonehead06 Would you mind pointing me out to some resources as to how I can do that?

**Comment by brianupskill** [comment]
@bonehead06 
Pod1:
```
17:52:55,799 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000078: Starting JGroups channel ejb
17:52:55,841 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000078: Starting JGroups channel ejb
17:52:55,891 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-0|0] (1) [kc1-keycloak-0]
17:52:55,897 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000079: Channel ejb local address is kc1-keycloak-0, physical addresses are [127.0.0.1:55200]
17:52:55,900 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-0|0] (1) [kc1-keycloak-0]
17:52:55,903 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000079: Channel ejb local address is kc1-keycloak-0, physical addresses are [127.0.0.1:55200]
17:52:55,909 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-1) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.8.Final
17:52:55,983 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000078: Starting JGroups channel ejb
17:52:55,986 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-0|0] (1) [kc1-keycloak-0]
17:52:55,987 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000079: Channel ejb local address is kc1-keycloak-0, physical addresses are [127.0.0.1:55200]
17:52:56,066 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000078: Starting JGroups channel ejb
17:52:56,068 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-0|0] (1) [kc1-keycloak-0]
17:52:56,068 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000079: Channel ejb local address is kc1-keycloak-0, physical addresses are [127.0.0.1:55200]
17:52:56,098 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000078: Starting JGroups channel ejb
17:52:56,139 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-0|0] (1) [kc1-keycloak-0]
17:52:56,143 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000079: Channel ejb local address is kc1-keycloak-0, physical addresses are [127.0.0.1:55200]
```

Pod2:
```
17:54:53,894 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000078: Starting JGroups channel ejb
17:54:53,897 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000078: Starting JGroups channel ejb
17:54:53,925 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-1|0] (1) [kc1-keycloak-1]
17:54:53,965 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-1|0] (1) [kc1-keycloak-1]
17:54:53,970 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000079: Channel ejb local address is kc1-keycloak-1, physical addresses are [127.0.0.1:55200]
17:54:53,971 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000079: Channel ejb local address is kc1-keycloak-1, physical addresses are [127.0.0.1:55200]
17:54:53,982 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-1) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.8.Final
17:54:54,081 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000078: Starting JGroups channel ejb
17:54:54,082 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-1|0] (1) [kc1-keycloak-1]
17:54:54,084 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000079: Channel ejb local address is kc1-keycloak-1, physical addresses are [127.0.0.1:55200]
17:54:54,123 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000078: Starting JGroups channel ejb
17:54:54,165 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-1|0] (1) [kc1-keycloak-1]
17:54:54,166 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000079: Channel ejb local address is kc1-keycloak-1, physical addresses are [127.0.0.1:55200]
17:54:54,182 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000078: Starting JGroups channel ejb
17:54:54,182 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [kc1-keycloak-1|0] (1) [kc1-keycloak-1]
17:54:54,182 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000079: Channel ejb local address is kc1-keycloak-1, physical addresses are [127.0.0.1:55200]
```

**Comment by bonehead06** [comment]
@brianupskill It looks like you and I are experiencing the same issues... the pods don't seem to be discovering each other with the headless service.

**Comment by brianupskill** [comment]
After a little more digging and debug I was able to find this in the log of the surviving pod after killing the other: 
```
21:36:55,444 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) [Context=offlineSessions][Scope=kc1-keycloak-0]ISPN100003: Finished local rebalance
21:36:55,445 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) ISPN000336: Finished cluster-wide rebalance for cache offlineSessions, topology id = 12
21:36:55,446 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) [Context=clientSessions][Scope=kc1-keycloak-0]ISPN100003: Finished local rebalance
21:36:55,447 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) ISPN000336: Finished cluster-wide rebalance for cache clientSessions, topology id = 12
21:36:55,458 INFO  [org.infinispan.CLUSTER] (remote-thread--p3-t2) [Context=client-mappings][Scope=kc1-keycloak-0]ISPN100003: Finished local rebalance
21:36:55,458 INFO  [org.infinispan.CLUSTER] (remote-thread--p3-t2) ISPN000336: Finished cluster-wide rebalance for cache client-mappings, topology id = 12
21:36:55,473 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) [Context=actionTokens][Scope=kc1-keycloak-0]ISPN100003: Finished local rebalance
21:36:55,473 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) ISPN000336: Finished cluster-wide rebalance for cache actionTokens, topology id = 12
21:36:55,554 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) [Context=sessions][Scope=kc1-keycloak-0]ISPN100003: Finished local rebalance
21:36:55,555 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) ISPN000336: Finished cluster-wide rebalance for cache sessions, topology id = 12
21:36:55,563 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) [Context=loginFailures][Scope=kc1-keycloak-0]ISPN100003: Finished local rebalance
21:36:55,564 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) ISPN000336: Finished cluster-wide rebalance for cache loginFailures, topology id = 12
21:36:55,567 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) [Context=work][Scope=kc1-keycloak-0]ISPN100003: Finished local rebalance
21:36:55,567 INFO  [org.infinispan.CLUSTER] (remote-thread--p4-t8) ISPN000336: Finished cluster-wide rebalance for cache work, topology id = 12
21:38:38,680 WARN  [org.infinispan.CLUSTER] (remote-thread--p4-t8) [Context=offlineClientSessions]ISPN000312: Lost data because of graceful leaver kc1-keycloak-0
21:38:38,744 WARN  [org.infinispan.CLUSTER] (remote-thread--p4-t14) [Context=clientSessions]ISPN000312: Lost data because of graceful leaver kc1-keycloak-0
```
Why would I lose any data in the clientSessions when I specifically set the owners to 2? Is this the intended behavior?

I also found a similar post here: http://lists.jboss.org/pipermail/keycloak-user/2018-April/013689.html

**Comment by bonehead06** [comment]
Interesting... I don't get any of those logs when I scale down/up.  What version of keycloak do you have in your values.yaml?

**Comment by brianupskill** [comment]
Keycloak 3.4.3.Final

**Comment by bonehead06** [comment]
Ahhh... that would explain some of the differences I'm seeing in my logs from you... I'm using 4.8.2.  Still it appears that the issue is with K8s + JGroups communications.

**Comment by zerthimon** [comment]
@bonehead06 @brianupskill 
Have any of you guys solved this issue ?
I've bin hit by it today. Any suggestions what to do with this or just dump the HA part altogether ?

**Comment by thomasdarimont** [comment]
Hello, I just gave this a spin.

I just deployed a 3-Node Keycloak cluster on Azure AKS and deleted one pod, which is automatically recreated a few seconds later.

Then I see the following information in the log:
```
keycloak-2 keycloak 17:22:48,004 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 60) WFLYCLINF0002: Started keys cache from keycloak container
keycloak-2 keycloak 17:22:48,005 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 64) WFLYCLINF0002: Started users cache from keycloak container
keycloak-2 keycloak 17:22:48,010 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 57) WFLYCLINF0002: Started realms cache from keycloak container
keycloak-2 keycloak 17:22:48,011 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 62) WFLYCLINF0002: Started authorization cache from keycloak container
keycloak-1 keycloak 17:22:48,073 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t22) [Context=clientSessions] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 45
keycloak-1 keycloak 17:22:48,102 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t26) [Context=sessions] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 46
keycloak-1 keycloak 17:22:48,108 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t25) [Context=loginFailures] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 47
keycloak-1 keycloak 17:22:48,107 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t28) [Context=offlineClientSessions] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 48
keycloak-1 keycloak 17:22:48,107 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=work] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 27
keycloak-1 keycloak 17:22:48,103 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t30) [Context=authenticationSessions] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 47
keycloak-1 keycloak 17:22:48,104 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t23) [Context=offlineSessions] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 46
keycloak-1 keycloak 17:22:48,110 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t22) [Context=actionTokens] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 47
keycloak-1 keycloak 17:22:48,312 INFO  [org.infinispan.CLUSTER] (remote-thread--p17-t1) [Context=client-mappings] ISPN100002: Starting rebalance with members [keycloak-1, keycloak-0, keycloak-2], phase READ_OLD_WRITE_ALL, topology id 27
keycloak-1 keycloak 17:22:49,814 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=work] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 28
keycloak-1 keycloak 17:22:50,090 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=work] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 29
keycloak-1 keycloak 17:22:50,101 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=sessions] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 47
keycloak-1 keycloak 17:22:50,103 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=offlineSessions] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 47
keycloak-1 keycloak 17:22:50,104 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=actionTokens] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 48
keycloak-1 keycloak 17:22:50,106 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=clientSessions] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 46
keycloak-1 keycloak 17:22:50,391 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t23) [Context=clientSessions] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 47
keycloak-1 keycloak 17:22:50,391 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t22) [Context=actionTokens] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 49
keycloak-1 keycloak 17:22:50,391 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t30) [Context=sessions] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 48
keycloak-1 keycloak 17:22:50,392 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=work] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 30
keycloak-1 keycloak 17:22:50,392 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t28) [Context=offlineSessions] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 48
keycloak-1 keycloak 17:22:50,394 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=offlineClientSessions] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 49
keycloak-1 keycloak 17:22:50,395 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=authenticationSessions] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 48
keycloak-1 keycloak 17:22:50,399 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t28) [Context=loginFailures] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 48
keycloak-2 keycloak 17:22:50,642 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 63) WFLYCLINF0002: Started work cache from keycloak container
keycloak-1 keycloak 17:22:50,692 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t27) [Context=sessions] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 49
keycloak-1 keycloak 17:22:50,693 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t22) [Context=offlineClientSessions] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 50
keycloak-1 keycloak 17:22:50,693 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t25) [Context=authenticationSessions] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 49
keycloak-1 keycloak 17:22:50,693 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t23) [Context=clientSessions] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 48
keycloak-1 keycloak 17:22:50,692 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t30) [Context=offlineSessions] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 49
keycloak-1 keycloak 17:22:50,692 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t26) [Context=loginFailures] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 49
keycloak-1 keycloak 17:22:50,697 INFO  [org.infinispan.CLUSTER] (remote-thread--p17-t1) [Context=client-mappings] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 28
keycloak-1 keycloak 17:22:50,696 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t28) [Context=actionTokens] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 50
keycloak-1 keycloak 17:22:50,993 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t26) [Context=offlineClientSessions] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 51
keycloak-1 keycloak 17:22:50,993 INFO  [org.infinispan.CLUSTER] (remote-thread--p17-t1) [Context=client-mappings] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 29
keycloak-1 keycloak 17:22:50,993 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t28) [Context=authenticationSessions] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 50
keycloak-1 keycloak 17:22:50,993 INFO  [org.infinispan.CLUSTER] (remote-thread--p5-t30) [Context=loginFailures] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 50
keycloak-2 keycloak 17:22:51,000 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 61) WFLYCLINF0002: Started actionTokens cache from keycloak container
keycloak-2 keycloak 17:22:51,001 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 56) WFLYCLINF0002: Started clientSessions cache from keycloak container
keycloak-2 keycloak 17:22:51,000 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 54) WFLYCLINF0002: Started offlineSessions cache from keycloak container
keycloak-2 keycloak 17:22:51,004 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 58) WFLYCLINF0002: Started sessions cache from keycloak container
keycloak-2 keycloak 17:22:51,236 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 52) WFLYCLINF0002: Started offlineClientSessions cache from keycloak container
keycloak-2 keycloak 17:22:51,237 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 59) WFLYCLINF0002: Started authenticationSessions cache from keycloak container
keycloak-2 keycloak 17:22:51,242 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 55) WFLYCLINF0002: Started loginFailures cache from keycloak container
keycloak-1 keycloak 17:22:51,294 INFO  [org.infinispan.CLUSTER] (remote-thread--p17-t1) [Context=client-mappings] ISPN100010: Finished rebalance with members [keycloak-1, keycloak-0, keycloak-2], topology id 30
keycloak-2 keycloak 17:22:51,538 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 60) WFLYCLINF0002: Started client-mappings cache from ejb container
```

**Comment by zerthimon** [comment]
@thomasdarimont Nice, I still can't get two replicas "see" each other.
Could you, please, share values.yaml you used with chart ?

**Comment by bernardgut** [comment]
did any of you manage to fix this ? I have the same issue...

**Comment by Stalluri1** [comment]
Hey can someone help on this , we are facing similar issue

**Comment by juv** [comment]
We have a similar issue, but our Keycloak instances appear to be able to join the jgroups cluster when looking at the log output. Our issue is that login sessions are not properly synchronized across the nodes. Basically, when obtaining a authorization code from the /auth endpoint, then sending it in to the /token endpoint, will end up in a `invalid_token` error in 9/10 times and the logs say that the authorization code has already been used. We have not yet figured out why this happens. Is this a sort of "race condition" where our client accesses the /token endpoint too fast and (due to loadbalancing) hits another instance than the instance that issued the authorization code? 

For example: instance keycloak-0 issues the authorization code, our client sends that auth code to the load balanced /token endpoint, keycloak-1 receives the auth code and does not yet know anything about the login session this auth code is bound to?

**Comment by huegelc** [comment]
@juv you have to configure keycloak using TCP instead of UDP

```
<subsystem xmlns="urn:jboss:domain:jgroups:6.0">
            <channels default="ee">
                <channel name="ee" stack="tcp" cluster="ejb"/>
            </channels>
```
We are using KUBE_PING

**Comment by juv** [comment]
@huegelc If I am not mistaken, the Helm chart is already doing this? 
https://github.com/helm/charts/blob/master/stable/keycloak/scripts/ha.cli#L8

**Comment by huegelc** [comment]
Yes, I see. The only difference is that we didn't deploy KC via helm chart but with Kube_Ping and configmaps.
The issue you reported was pretty much identical to ours, so we changed the configuration to TCP and it worked.

**Comment by cassador** [comment]
To fix your issue you need to specify your service following:

apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: testing
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jdbc
    port: 9101
    protocol: TCP
    targetPort: 9101
  - name: discovery
    port: 7600
    targetPort: 7600
  selector:
    app: keycloak
  sessionAffinity: None
status:


And the part of the ENV_Variables  for keycloak needs to container following:
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: "dns_query=keycloak.testing.svc.cluster.local"

**Comment by zerthimon** [comment]
@cassador that should already be specified in the helm templates.

**Comment by frittentheke** [comment]
@cassador  I added configurability for this via https://issues.redhat.com/browse/KEYCLOAK-10151 or rather https://github.com/keycloak/keycloak-containers/pull/192 . Those ENV properly set by the helm-chart should be sufficient, no need to configure things "manually".
