### ISSUE TITLE
[stable/graylog] Deprecated API version for Kubernetes 1.16

### ISSUE THREAD

**Issue by CaptainKrby** [helm/charts#18997]
Hello, I recently updated the kubernetes cluster (1.16) which hosted Graylog and during a redeploy one day later I was confronted with this error:

`Failed to install app graylog. Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"] `

I suspect the mongo and elasticsearch charts that still have deprecated fields (apps/v1beta1).
Could you update the Graylog chart to link them with the version that supports kubernetes 1.16 ?

Thanks

**Comment by juliohm1978** [comment]
I'm having the same problem. Using helm3 with chart version 1.5.0.

A `helm diff` puts the blame on the mongodb replicaset.

```diff
default, graylog-mongodb-replicaset, StatefulSet (apps) has been added:
+ # Source: graylog/charts/mongodb-replicaset/templates/mongodb-statefulset.yaml
+ apiVersion: apps/v1beta2
```

I do, however, have the chart configured to NOT install elasticsearch or mongo.

```yaml
tags:
  # If true, this chart will install Elasticsearch from requirement dependencies
  install-elasticsearch: false
  # If true, this chart will install MongoDB replicaset from requirement dependencies
  install-mongodb: false
```
That seems to have no effect.

**Comment by rroseselavy42** [comment]
can report same issue

**Comment by kjake** [comment]
Seeing the same with v1.16.3

**Comment by juliohm1978** [comment]
The API version from the mongodb-replicaset seems to be have been fixed over a year ago.

https://github.com/helm/charts/commit/1579053c864a87d11e0c87331d8dab7d669f47a1#diff-9707ad19eeff7b95904599011488b0d1

The requirements on the graylog chart should've been updated a long time ago, but it's still using version mongodb-replicaset chart v3.8.4.

**Comment by juliohm1978** [comment]
PR #20005 is on the way.

**Comment by kjake** [comment]
This doesn't fix the overall issue.  requirements.yaml still calls for elasticsearch-1.15.0, which has the same problem as mongodb-replicaset.  requirements.yaml needs to be updated to call for elasticsearch-1.32.0 at a minimum, or 1.32.1 which is the latest.
