### ISSUE TITLE
[stable/pgadmin] support for spec.strategy.rollingUpdate.maxSurge=0

### ISSUE THREAD

**Issue by mfbrj** [helm/charts#20522]
**Is your feature request related to a problem? Please describe.**
VSphere provider supports only 1 pod mounting a persistent volume at the same time. When starting a second pod, it fails with a mounting error and the deployment crashs over and over again.

**Describe the solution you'd like**
It would be nice if `values.yml` supported an option to set `spec.strategy.rollingUpdate.maxSurge=0` on `deployment.yml`, in order to the deployment first stop old pods, then start new.

**Describe alternatives you've considered**

**Additional context**

**Comment by rowanruseler** [comment]
@fredbeltrao sure thing, this is easy done - I'll setup a pull request later-on today.

**Comment by rowanruseler** [comment]
@fredbeltrao implemented and merged: https://github.com/helm/charts/pull/20533

**Comment by fredbeltrao** [comment]
I used thes values:
```
---
replicaCount: 1
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
  hosts:
  - host: pgadmin.tre-pa.jus.br
    paths:
      - /
  tls:
    - secretName: asterisco-tre-pa
      hosts:
        - pgadmin.tre-pa.jus.br
env:
  email: fbeltrao@tre-pa.jus.br
  password: SuperSecret
  
persistentVolume:
  enabled: true
  size: 1Gi
  storageClass: "-"
  existingClaim: "pgadmin"
  
tolerations:
- key: "persistent"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
  
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
```

And get this error:
`Failed to install app pgadmin. Error: UPGRADE FAILED: YAML parse error on pgadmin/templates/deployment.yaml: error converting YAML to JSON: yaml: line 21: did not find expected key`

**Comment by rowanruseler** [comment]
@fredbeltrao so sorry.. it looks like I never learn! Should be resolved once: https://github.com/helm/charts/pull/20540 is merged. Apologies.

**Comment by rowanruseler** [comment]
@fredbeltrao looks like it is merged, so please give it another attempt and let me know if it still not working at your end.

**Comment by fredbeltrao** [comment]
What template version? My Rancher cluster is still showing version 1.1.3.

**Comment by rowanruseler** [comment]
Version 1.1.3 is correct, I just tested it again and it functioned.

**Comment by fredbeltrao** [comment]
I tested here and it's ok! Thanks @rowanruseler
