### ISSUE TITLE
[stable/prometheus-operator] AggregatedAPIDown rule only for k8s >= 1.18

### ISSUE THREAD

**Issue by Delorien84** [helm/charts#22948]
AggregatedAPIDown rule constantly fire on kubernetes < 1.18 due to k8s bug fixed in 1.18. See https://github.com/kubernetes/kubernetes/pull/87778 and  https://github.com/kubernetes/kube-aggregator/issues/23.

Helm chart should enable the rule only for kubernetes >= 1.18

**Comment by den-is** [comment]
initial it was addressed here:
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/397
so please make noise there too
 
also, there is slightly related issues https://github.com/helm/charts/issues/22081
they are not super active on fixing and syncing https://github.com/kubernetes-monitoring/kubernetes-mixin
into
https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml

**Comment by lyz-code** [comment]
bump

**Comment by JessieAMorris** [comment]
I'm still seeing it as well. We updated our k8s version to 1.15 and now this is always firing.

**Comment by shaahmed115** [comment]
Experiencing this as well, Kubernetes 1.16. Can this be prioritized somehow, or is this not the right place to ask for it?

**Comment by skalolazka** [comment]
Experiencing this as well, Kubernetes 1.16. Can this be prioritized somehow, or is this not the right place to ask for it?

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
