### ISSUE TITLE
[stable/airflow] an extra newline character \n is added to the end of the value of scheduler.existingSecretConnections causing scheduler pod initialization to fail

### ISSUE THREAD

**Issue by tinhkyaw** [helm/charts#23856]
There seems to be an extra newline character `\n` being added to the value for `scheduler.existingSecretConnections` somewhere during the deployment.  I created an secret named `airflow-dev` containing an `add-connections.sh` script but once I added my secret name to `scheduler.existingSecretConnections`, the scheduler pod initialization failed with the following error:

```MountVolume.SetUp failed for volume "connections" : secret "airflow-dev\n" not found```

**Version of Helm and Kubernetes**:
Helm Version: `version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}`

Kubernetes Version: `1.17`

**Which chart**:
stable/airflow

**What happened**:
An extra newline character `\n` is added to the end of the value of `scheduler.existingSecretConnections` causing scheduler pod initialization to fail.  

**What you expected to happen**:
There should not be an extra newline character `\n` being added to the end of the value of `scheduler.existingSecretConnections` causing scheduler pod initialization to fail.

**How to reproduce it** (as minimally and precisely as possible):
Add any valid secret name as a value to `scheduler.existingSecretConnections` and try installing the chart

**Comment by tinhkyaw** [comment]
This has been fixed in: https://github.com/helm/charts/pull/23858

**Comment by pingdink** [comment]
Hi! ... 

Any idea why it still isn't fixed for us....???

We have the following in our chart:

scheduler:
  connections:
    - id: aws_default
      type: aws
      extra: |
        {
          "aws_access_key_id": "XXXXXX",
          "aws_secret_access_key": "XXXXXX",
          "region_name":"XXXX"
        }

and the following is from our airflow connections...
{\n  "aws_access_key_id": "XXXXXXX",\n  "aws_secret_access_key": "XXXXXXXXX",\n  "region_name":"us-east-2"\n}\n

helm list:
NAME        NAMESPACE   REVISION    UPDATED                                                       STATUS     CHART                 APPVERSION
airflow       default             8                  2020-10-14 12:52:16.923177 -0700 PDT   deployed    airflow-7.11.3       1.10.12
