### ISSUE TITLE
Persistent Volume Errors with Spinnaker Helm Chart 

### ISSUE THREAD

**Issue by grizzthedj** [helm/charts#3210]
**This a request for help**:
I'm trying to install spinnaker into my Kubernetes cluster using the [Helm Chart](https://github.com/kubernetes/charts/tree/master/stable/spinnaker), and am running into issues. The pods for the spinnaker services get created, but it seems that the services that require persistence(redis, minio & jenkins) fail to startup because of persistent volume related issues. The persistent volume "claims" get created, however, they are all stuck in a `Pending` state.

Should I expect the Helm Chart to create these volumes, or is this something that needs to be configured prior to running `helm install`? If so, is this to be configured in the `values.yml` file, then passed to `helm install`? 

**Version of Helm and Kubernetes**:
Helm version: `v2.7.2`
Kubernetes version: `1.9`

**Which chart**:
`stable/spinnaker`

**What happened**:
Attempted to install spinnaker into Kubernetes cluster using the helm chart at https://github.com/kubernetes/charts/tree/master/stable/spinnaker. Used the command below to install spinnaker. After several minutes it times out with `Error: timed out waiting for the condition`. I tried again, increasing the timeout to 2000, and same result.

`helm install --name spinnaker --namespace spinnaker stable/spinnaker --timeout 600`

Looking at the pods that are created, the `minio`, `redis` and `jenkins` services have the following error message(all 3 the same)

`Unable to mount volumes for pod "spinnaker-minio-7696669847-5wmj4_spinnaker(dff8d5cf-f0c0-11e7-9a6b-ecf4bbc5777c)": timeout expired waiting for volumes to attach/mount for pod "spinnaker"/"spinnaker-minio-7696669847-5wmj4". list of unattached/unmounted volumes=[export]`

**What you expected to happen**:
I expected to have spinnaker services installed in Kubernetes with persistence setup successfully, and all pods in a `Running` state. 

**How to reproduce it** (as minimally and precisely as possible):
1). Create a K8s cluster(1 master, 2 minions) on CentOS 7, using `kubeadm` on 3 bare metal nodes
2). Install helm on the master node
3). Create `serviceaccount`, and `clusterrolebinding` for `tiller` 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
```

4). From the master node: `helm install --name spinnaker --namespace spinnaker stable/spinnaker --timeout 600`

**Comment by rossedman** [comment]
@grizzthedj Did you set up Gluster or Ceph to be able to use Persistent Volumes on bare metal? There is some extra work involved in doing this.

**Comment by grizzthedj** [comment]
I was hoping to be able to use an NFS server(external to K8s) for storage. The NFS server is up and running, but not sure how to tell Helm to use NFS.

**Comment by rossedman** [comment]
@grizzthedj These are the storage classes available to k8s. To do NFS, I believe k8s would be unaware of it and it wouldn't be a persistent volume and would just be a local mount: https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by agnnn** [comment]
Even I was facing this same issue while deploying Spinnaker on Azure AKS cluster using Helm chart. When i used default values.yaml the storage error was fixed. But now i am getting this error 

> post-install spinnaker/templates/hooks/upload-build-image.yaml could not complete: timed out waiting for the condition

**Comment by rossedman** [comment]
@agnnn Azure has other problems with volume mounts. Might check what the default storage account is called in Azure versus the Helm chart.

**Comment by chrisgoffinet** [comment]
I am seeing this exact issue as well but under GKE 1.9.2

**Comment by mrumpf** [comment]
Not sure whether this is related, but there are 'pod has unbound PersistentVolumeClaims' errors on Minikube as well (Jenkins, minio, and redis).
My first idea was that the default size of 20GB of the Minikube VM disk does not allow for persistent volume groups of 2x8GB and 1x10GB to be created. But after increasing the Minikube VM size to 30GB the issue still occurs.

**Comment by mercantiandrea** [comment]
I have the same problem with k8s 1.10.5 installed with kops on AWS. 
M5 family instances and ami k8s-1.10-Debian-Stretch

**Comment by vmalhotra22** [comment]
I got the same error :(

The following I tried but still it fails.

helm install --name my-release stable/spinnaker --debug --namespace spinnaker
[debug] Created tunnel using local port: '59058'
[debug] SERVER: "127.0.0.1:59058"
[debug] Original chart version: ""
[debug] Fetched stable/spinnaker to /Users/varun.malhotra/.helm/cache/archive/spinnaker-0.5.0.tgz
[debug] CHART PATH: /Users/varun.malhotra/.helm/cache/archive/spinnaker-0.5.0.tgz
Error: timed out waiting for the condition

Can anyone help me with the same please.
Cheers

**Comment by hsafe** [comment]
Hi,
I did get the same error, mine is a bit different. I ran a minikube install on ArchLinux install with KVM2 driver. Natively the default name space gets a cluster of Minio set up and running. Following install instruction from [here]([https://thenewstack.io/getting-started-spinnaker-kubernetes/])eventually and after a long retry with the timeouts and running:
helm del --purge kubelive
Here is what I got stuck at:

```
NAME                                             READY     STATUS                  RESTARTS   AGE
hal-deploy-apply-zqxds                           0/1       Error                   38         13h
kubelive-create-bucket-zlv7j                     0/1       CrashLoopBackOff        7          19m
kubelive-jenkins-79955b657d-65bpz                0/1       Init:CrashLoopBackOff   7          19m
kubelive-minio-6b5ccff4b9-z2d2g                  0/1       CrashLoopBackOff        8          19m
kubelive-redis-674745564-jpjf5                   1/1       Running                 0          19m
kubelive-spinnaker-clouddriver-8cbcf8bbd-8tgx9   1/1       Running                 0          19m
kubelive-spinnaker-deck-754d5fbb7b-cdd7h         1/1       Running                 0          19m
kubelive-spinnaker-echo-76b54f4d5d-bh24q         0/1       Running                 0          19m
kubelive-spinnaker-front50-75ccf59d87-tndmr      0/1       Running                 8          19m

```

**Comment by cpanato** [comment]
i guess was fixed here: https://github.com/helm/charts/pull/7462

**Comment by cpanato** [comment]
can close
/close

**Comment by nennete** [comment]
Hi, I am experiencing the same issue.
The PR did not solve the problem.
In our case, the problem comes with the halyard StatefufSet. In there, the `PersistentVolumeClaimTemplate` is declared. But the chart does not allow to manipulate it. I.e. Adding more annotations required to make it work with Gluster. `storage-class`

Here the piece of code in the chart: https://github.com/helm/charts/blob/master/stable/spinnaker/templates/statefulsets/halyard.yaml#L98

It would be good to have something like:
https://github.com/helm/charts/blob/master/stable/postgresql/templates/pvc.yaml#L13

Thank you
