### ISSUE TITLE
[incubator/elasticsearch] Elasticsearch 2.4 elasticsearch-client never reaches minimum availability: master not discovered

### ISSUE THREAD

**Issue by phidah** [helm/charts#4151]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report.

**Version of Helm and Kubernetes**:
Kubernetes nodes: v1.9.3-gke.0
Kubernetes master: v1.9.3-gke.0
Helm version: 

**Which chart**:
incubator/elasticsearch

**What happened**:
If I create the release using `helm install --set image.tag=2.4 --name elasticsearch incubator/elasticsearch`, the `elasticsearch-client` deployment never reaches full availability, 

Full logs from GKE:

Container | Timestamp | Message
-- | -- | --
elasticsearch | Mar 14, 2018, 11:14:30 AM | at java.lang.Thread.run(Thread.java:748)
elasticsearch | Mar 14, 2018, 11:14:30 AM | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elasticsearch | Mar 14, 2018, 11:14:30 AM | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elasticsearch | Mar 14, 2018, 11:14:30 AM | at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:816)
elasticsearch | Mar 14, 2018, 11:14:30 AM | at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:236)
elasticsearch | Mar 14, 2018, 11:14:30 AM | at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$5.onTimeout(TransportMasterNodeAction.java:234)
elasticsearch | Mar 14, 2018, 11:14:30 AM | MasterNotDiscoveredException[null]
elasticsearch | Mar 14, 2018, 11:14:30 AM | [2018-03-14 10:14:30,170][WARN ][rest.suppressed ] path: /_cluster/health, params: {wait_for_status=yellow}
elasticsearch | Mar 14, 2018, 11:14:30 AM | [2018-03-14 10:14:30,170][DEBUG][action.admin.cluster.health] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] timed out while retrying [cluster:monitor/health] after failure (timeout [30s])
elasticsearch | Mar 14, 2018, 11:14:30 AM | [2018-03-14 10:14:30,168][DEBUG][action.admin.cluster.health] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] no known master node, scheduling a retry
elasticsearch | Mar 14, 2018, 11:14:20 AM | at java.lang.Thread.run(Thread.java:748)
elasticsearch | Mar 14, 2018, 11:14:20 AM | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elasticsearch | Mar 14, 2018, 11:14:20 AM | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elasticsearch | Mar 14, 2018, 11:14:20 AM | at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:816)
elasticsearch | Mar 14, 2018, 11:14:20 AM | at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:236)
elasticsearch | Mar 14, 2018, 11:14:20 AM | at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$5.onTimeout(TransportMasterNodeAction.java:234)
elasticsearch | Mar 14, 2018, 11:14:20 AM | MasterNotDiscoveredException[null]
elasticsearch | Mar 14, 2018, 11:14:20 AM | [2018-03-14 10:14:20,308][WARN ][rest.suppressed ] path: /_cluster/health, params: {wait_for_status=yellow}
elasticsearch | Mar 14, 2018, 11:14:20 AM | [2018-03-14 10:14:20,299][DEBUG][action.admin.cluster.health] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] timed out while retrying [cluster:monitor/health] after failure (timeout [30s])
elasticsearch | Mar 14, 2018, 11:14:20 AM | [2018-03-14 10:14:20,169][DEBUG][action.admin.cluster.health] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] no known master node, scheduling a retry
elasticsearch | Mar 14, 2018, 11:14:10 AM | [2018-03-14 10:14:10,168][DEBUG][action.admin.cluster.health] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] no known master node, scheduling a retry
elasticsearch | Mar 14, 2018, 11:14:00 AM | [2018-03-14 10:14:00,169][DEBUG][action.admin.cluster.health] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] no known master node, scheduling a retry
elasticsearch | Mar 14, 2018, 11:13:50 AM | [2018-03-14 10:13:50,296][DEBUG][action.admin.cluster.health] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] no known master node, scheduling a retry
elasticsearch | Mar 14, 2018, 11:13:41 AM | [2018-03-14 10:13:41,900][INFO ][node ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] started
elasticsearch | Mar 14, 2018, 11:13:41 AM | [2018-03-14 10:13:41,900][INFO ][http ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] publish_address {10.52.48.29:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch | Mar 14, 2018, 11:13:41 AM | [2018-03-14 10:13:41,894][WARN ][discovery ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] waited for 30s and no initial state was set by the discovery
elasticsearch | Mar 14, 2018, 11:13:11 AM | [2018-03-14 10:13:11,891][INFO ][discovery ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] elasticsearch/qMDd7wAZStmlh9apOQccig
elasticsearch | Mar 14, 2018, 11:13:11 AM | [2018-03-14 10:13:11,885][INFO ][transport ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] publish_address {10.52.48.29:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch | Mar 14, 2018, 11:13:11 AM | [2018-03-14 10:13:11,758][INFO ][node ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] starting ...
elasticsearch | Mar 14, 2018, 11:13:11 AM | [2018-03-14 10:13:11,709][INFO ][node ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] initialized
elasticsearch | Mar 14, 2018, 11:13:06 AM | [2018-03-14 10:13:06,505][INFO ][plugins ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] modules [reindex, lang-expression, lang-groovy], plugins [kopf, cloud-kubernetes], sites [kopf]
elasticsearch | Mar 14, 2018, 11:13:05 AM | [2018-03-14 10:13:05,608][INFO ][node ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] initializing ...
elasticsearch | Mar 14, 2018, 11:13:05 AM | [2018-03-14 10:13:05,607][INFO ][node ] [elasticsearch-elasticsearch-client-89c57b8fb-5ljsl] version[2.4.5], pid[1], build[c849dd1/2017-04-24T16:18:17Z]

When I run the newest version of Elasticsearch the cluster works as expected.

**What you expected to happen**:
Cluster is normal after a couple of minutes.

**How to reproduce it** (as minimally and precisely as possible):
`helm install --set image.tag=2.4 --name elasticsearch incubator/elasticsearch`
I am unsure whether this is a GKE specific issue.
Works fine with newer versions.

**Anything else we need to know**:

**Comment by bg-makbarof** [comment]
+1
Have the same issue with 2.4

**Comment by tonyfahrion** [comment]
Hi @phidah, might this be an RBAC problem? It worked for us internally  with GKE `1.9.3` and ES `2.4`

**Comment by phidah** [comment]
I am not sure. In the meantime I migrated to Elasticsearch 6 so the problem was solved 👍

**Comment by tonyfahrion** [comment]
As far as I can tell; this is because the the initial first master POD tries to do master-discovery via the service resource. But as the master-POD is still not in READY state, the service got no endpoints - so discovery fails.
I solved this by adding `publishNotReadyAddresses: true` to the `master-svc.yaml` file. In addition this makes the kubernetes plugin obsolete so even the ES docker images form the official library are working now.

The project https://github.com/fabric8io/elasticsearch-cloud-kubernetes also recommends to not use the kubernetes plugin and instead using a headless service: https://github.com/fabric8io/elasticsearch-cloud-kubernetes#kubernetes-cloud-plugin-for-elasticsearch
