### ISSUE TITLE
[dokuwiki chart] Using tls in ingress should set serviceport to 443

### ISSUE THREAD

**Issue by LecygneNoir** [helm/charts#7908]
Hello!

This is concerning the dokuwiki chart, but possibly impact others as this is a general ingress problem (not specific to dokuwiki app)
 
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: helm 2.9.1 with k8s 1.11

**Which chart**: dokuwiki

**What happened**:
When enabling the ingress tls for the chart, it automatically allow ingress.kubernetes.io/secure-backends: "true"
However, the ingress is still created on the port 80 and not on the port 443.

This break http check from ingress, and so the ingress-controller consider the service unreachable, as it tries to reach https on port 80.  

**What you expected to happen**:
When enabling tls for the ingress, serviceport should be set to 443

**How to reproduce it** (as minimally and precisely as possible):
 - Install a release while enabling `tls: true` in the ingress part
 - get the ingress on k8s cluster
 - `ingress.kubernetes.io/secure-backends` is correclty set to "true" in annotations
 - However, the spec-rules part still describe the backend using the port 80, which cannot work

**Anything else we need to know**:
This problem possibly impact others charts, as this seems a general bug when generating the ingress with SSL. Possibly, it has already been solved for others charts, but I found no corresponding issues in the github. 

Sorry in advance if I have missed one, but still the bug is present for dokuwiki :-)

Anyway, thank you for your work on these charts! Really great job.

Regards,

**Comment by LecygneNoir** [comment]
Hello there :)

Is there any chance this issue is solved?

Thanks!

**Comment by tompizmor** [comment]
@LecygneNoir Sorry for the late response. Where exactly are you seeing the error? I deployed dokuwiki enabling ingress and tls but I don't see any HTTP healtcheck failing.

**Comment by LecygneNoir** [comment]
Hello @tompizmor 

It's some month ago, but it seems the bug is still here.

When enabling the tls option in the chart, it triggers the option `ingress.kubernetes.io/secure-backends: "true"`

This option is added in the ingress when deploying, and it implies that the ingress controller do its healthcheck on a secure port (eg: 443)

But at the same time, the ingress is hardcoded to use port 80, where there is no SSL:

```
    http:
      paths:
      - backend:
          serviceName: dokuwiki-release-dokuwiki
          servicePort: 80
        path: /
```

Thus the healthcheck reach the service, tries to establish SSL session, failed, and it brokes the ingress process.

You could see here : https://github.com/helm/charts/blob/master/stable/dokuwiki/templates/ingress.yaml

The annotation `secure-backend` is added:

```
  annotations:
    {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
{{- end }}
[...]
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "dokuwiki.fullname" $ }}
            servicePort: 80
```

While the backend servicePort is 80. If your ingress support the secure-backend option (which it should :-) ) then it'll try SSL on the port 80, and the healthcheck will fail.

Using the secure-backend option is a really good practice for me, I guess it should add something like 

```
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "dokuwiki.fullname" $ }}
{{- if .tls }}
            servicePort: 443
{{-else }}
            servicePort: 80
{{-end }}
```

But I am really not familiar with the helm and yaml syntax and failed to made it works in my env (I finished by editing the ingress manually after deployment).

Hope it's more clear, and thank you again for all these charts :)

Regards
