### ISSUE TITLE
spinnaker chart has bug when in non-default namespace

### ISSUE THREAD

**Issue by patricklucas** [helm/charts#969]
When deleting a Spinnaker instance, the job started by the "delete-jobs" post-delete hook got stuck with the post-install-job container cycling between Error and CrashLoopBackOff.

I think the reason is that the job calls `kubectl` without `--namespace` (and presumably doesn't pick it up from the environment), and so is trying to kill jobs in the wrong namespace. I haven't actually verified this.

**Comment by viglesiasce** [comment]
Fixed in #961

**Comment by shimmerjs** [comment]
I'm still seeing this in post-install-job on 0.3.5, in all namespaces, even default.
